pipeline {
    agent {
        node {
            label 'docker-agent'
            }
      }
    tools {
        maven 'Maven'
    }
    stages {
        stage('Build') {
            steps {
                echo "Building with Maven..."

                sh "mvn clean package"
            }
        }
        stage('Test') {
            steps {
                echo "Running unit tests..."

                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo "Delivering..."

                sh './docker/jenkins/deliver.sh'
            }
        }
    }
}
